import type { FinanceData, CommercialData, MarketingData, OperationsData, InventoryData, BrandData } from './types';

export const financeData: FinanceData = {
  revenue: { mtd: 650482, target: 600000, daily: [18500, 19200, 21000, 22500, 20800, 21693, 23100, 19800, 22400, 21200, 20500, 23800, 22100, 21344, 19600, 22800, 21500, 23200, 20100, 22700, 21800, 20900, 23500, 22300, 21600, 19900, 23100, 22400, 21700, 20300, 21693], labels: ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31'] },
  grossProfit: { mtd: 307235, margin: 47.2 },
  operatingProfit: { mtd: 98421, margin: 15.1 },
  netProfit: { mtd: 67890, change: 4.8 },
  cashBalance: { current: 248000, change: -6.2 },
  debtors: { total: 1320000, change: -4 },
  creditors: { total: 2150000, change: 1.8 },
  inventoryValue: { total: 1180000, turnRatio: 1.62 },
  cashFlow: { inflow: 1850000, outflow: 1620000, net: 230000, trend: [180000, 195000, 210000, 225000, 230000] },
  expenses: {
    categories: [
      { name: 'Rent', actual: 170500, budget: 170000 },
      { name: 'Salaries', actual: 98200, budget: 95000 },
      { name: 'Marketing', actual: 16713, budget: 18000 },
      { name: 'Utilities', actual: 8450, budget: 9000 },
      { name: 'Logistics', actual: 13912, budget: 14500 },
      { name: 'Admin', actual: 5410, budget: 6000 },
      { name: 'Others', actual: 34210, budget: 34500 },
    ]
  },
  revenueByBrand: [
    { name: 'Boulevard Men', value: 262000 },
    { name: 'Boulevard Women', value: 104800 },
    { name: 'D\'Angelo', value: 97500 },
    { name: 'Woodpeckers', value: 84800 },
    { name: 'Carbon Shoes', value: 52200 },
    { name: 'Others', value: 49182 },
  ],
  profitability: {
    metrics: [
      { name: 'Revenue', mtd: 650482, ytd: 6125430, change: 8.4 },
      { name: 'COGS', mtd: 343247, ytd: 3229772, change: 5.2 },
      { name: 'Gross Profit', mtd: 307235, ytd: 2895658, change: 12.5 },
      { name: 'Operating Expenses', mtd: 208814, ytd: 1990415, change: 3.8 },
      { name: 'Operating Profit', mtd: 98421, ytd: 905243, change: 15.7 },
      { name: 'Other Income', mtd: 4300, ytd: 34480, change: 0.6 },
      { name: 'Finance Costs', mtd: 17231, ytd: 163598, change: -2.1 },
      { name: 'PBT', mtd: 85490, ytd: 776125, change: 12.3 },
      { name: 'Tax', mtd: 17600, ytd: 149460, change: 11.8 },
      { name: 'Net Profit', mtd: 67890, ytd: 626685, change: 4.8 },
    ]
  },
  workingCapital: { inventory: 1180000, debtors: 1320000, creditors: 2150000, ratio: 1.18 },
  cashRunway: 78,
  forecast: { revenue: 1860000, grossProfit: 880000, netProfit: 190000 },
  healthCheck: { profitability: 'Good', liquidity: 'Good', solvency: 'Low Risk', efficiency: 'Good', cashFlow: 'Positive' },
};

export const commercialData: CommercialData = {
  groupSales: { mtd: 650482, target: 1000000 },
  grossMargin: { pct: 47.8, target: 48 },
  atv: { value: 1116, target: 1200 },
  upt: { value: 1.16, target: 1.25 },
  conversionRate: { pct: 24.7, target: 28 },
  sellThrough: { pct: 68.3, target: 75 },
  activeSku: 12842,
  stores: [
    { rank: 1, name: 'Dzorwulu Men', sales: 118420, target: 100000, achievement: 74, vsLastMonth: -18.2 },
    { rank: 2, name: 'East Legon Men', sales: 102330, target: 100000, achievement: 74.8, vsLastMonth: 5.2 },
    { rank: 3, name: 'Labore Men', sales: 95860, target: 100000, achievement: 60.5, vsLastMonth: -1.3 },
    { rank: 4, name: 'Boulevard Women Labore', sales: 52810, target: 80000, achievement: 51.2, vsLastMonth: -12.2 },
    { rank: 5, name: 'Boulevard Women Dzorwulu', sales: 29630, target: 40000, achievement: 42, vsLastMonth: -8.5 },
    { rank: 6, name: 'D\'Angelo Palace', sales: 91250, target: 100000, achievement: 68.9, vsLastMonth: 11.5 },
    { rank: 7, name: 'Woodpeckers', sales: 116250, target: 180000, achievement: 64.5, vsLastMonth: 24.3 },
  ],
  categories: [
    { name: 'Suits', sales: 132450, achievement: 66.7, mix: 20.4 },
    { name: 'Shoes', sales: 55670, achievement: 70.4, mix: 8.6 },
    { name: 'Shirts', sales: 38120, achievement: 63.5, mix: 5.9 },
    { name: 'Blazers', sales: 38120, achievement: 57.1, mix: 5.9 },
    { name: 'Bags', sales: 24350, achievement: 48.7, mix: 3.7 },
    { name: 'Others', sales: 47632, achievement: 63.4, mix: 7.3 },
  ],
  topSelling: [
    { rank: 1, sku: 'ARB-101', name: 'Arbiter Oxford Black 42', sales: 26350, qty: 62 },
    { rank: 2, sku: 'BLA-201', name: 'Blazer Classic Navy 50', sales: 19830, qty: 45 },
    { rank: 3, sku: 'SHI-302', name: 'Shirt White Linen L', sales: 17620, qty: 89 },
    { rank: 4, sku: 'BAG-501', name: 'Leather Bag Brown', sales: 15400, qty: 33 },
    { rank: 5, sku: 'TRS-701', name: 'Trouser Grey 36', sales: 11950, qty: 52 },
  ],
  lowMoving: [
    { sku: 'BLU-S-Blue', description: 'Blazer S Blue', category: 'Blazers', days: 132, value: 4820 },
    { sku: 'BLA-201-NVY', description: 'Blazer Classic Navy 50', category: 'Blazers', days: 118, value: 4260 },
    { sku: 'SHI-302-WHT', description: 'Shirt White Linen L', category: 'Shirts', days: 104, value: 3450 },
    { sku: 'BAG-501-BRN', description: 'Leather Bag Brown', category: 'Bags', days: 98, value: 3280 },
    { sku: 'TRS-701-GRY', description: 'Trouser Grey 36', category: 'Trousers', days: 95, value: 2980 },
  ],
  deadStock: [
    { sku: 'BLA-201-BRG', description: 'Blazer Burgundy 52', category: 'Blazers', days: 245, value: 8220 },
    { sku: 'SWE-901-NVY', description: 'Sweater Knit Navy L', category: 'Sweaters', days: 223, value: 6800 },
    { sku: 'PJS-100-GRY', description: 'Pajama Set Grey M', category: 'Pajamas', days: 210, value: 5450 },
    { sku: 'WAT-601-BLK', description: 'Watch Classic Black', category: 'Watches', days: 198, value: 4950 },
    { sku: 'SHOE-900-BRG', description: 'Formal Shoe Burgundy', category: 'Shoes', days: 186, value: 3950 },
  ],
  newArrivals: [
    { brand: 'Arbiter', qty: 34, stockValue: 79540, sellThrough: 62 },
    { brand: 'D\'Angelo Butters', qty: 28, stockValue: 64520, sellThrough: 55 },
    { brand: 'Gianni Gallucci', qty: 22, stockValue: 48930, sellThrough: 48 },
    { brand: 'Cucinera Fiorentina', qty: 18, stockValue: 31600, sellThrough: 71 },
  ],
  focusProducts: [
    { name: 'Arbiter Collection', action: 'Live Awareness', owner: 'Marketing', deadline: '15 Jun', status: 'In Progress' },
    { name: 'Papas', action: 'Live Sell Through', owner: 'Merch Team', deadline: '21 Jun', status: 'In Progress' },
    { name: 'Winter Coats', action: 'End of Season', owner: 'Commercial', deadline: '30 Jun', status: 'Planned' },
  ],
  accountability: [
    { role: 'Head of Commercial', name: 'Adisa Mohammed', kpi: 'Sales Target Achievement', target: '100%', actual: 'GHS 650,482', achievement: 65, status: 'At Risk' },
    { role: 'Merchandise Manager', name: 'Daniel K.', kpi: 'Sell Through %', target: '75%', actual: '68.3%', achievement: 91, status: 'At Risk' },
    { role: 'Category Buyer - Mens', name: 'Isaac K.', kpi: 'GM %', target: '48%', actual: '47.8%', achievement: 99.6, status: 'On Track' },
    { role: 'Store Operations Lead', name: 'Kofi T.', kpi: 'Conversion Score', target: '30%', actual: '24.7%', achievement: 82.3, status: 'Off Track' },
  ]
};

export const marketingData: MarketingData = {
  brandHealth: [
    { brand: 'Boulevard Men', awareness: 88, preference: 84, sentiment: 87, score: 87 },
    { brand: 'Boulevard Women', awareness: 82, preference: 79, sentiment: 71, score: 82 },
    { brand: 'D\'Angelo', awareness: 72, preference: 70, sentiment: 71, score: 71 },
    { brand: 'Woodpeckers', awareness: 78, preference: 74, sentiment: 76, score: 76 },
    { brand: 'Carbon Shoes', awareness: 68, preference: 65, sentiment: 66, score: 66 },
  ],
  campaigns: [
    { name: 'The Rolex of Shoes', brand: 'Arbiter', reach: 324560, engagement: 28450, leads: 512, revenue: 98450 },
    { name: 'Wear What Moves The City', brand: 'Boulevard Men', reach: 289300, engagement: 24870, leads: 428, revenue: 76320 },
    { name: 'Designed To Be Passed On', brand: 'Woodpeckers', reach: 219120, engagement: 19420, leads: 310, revenue: 54210 },
    { name: 'D\'Angelo Professional Wardrobe', brand: 'D\'Angelo', reach: 160880, engagement: 14420, leads: 275, revenue: 54210 },
  ],
  acquisition: {
    whatsappLeads: 623, instagramLeads: 432, websiteLeads: 213, walkInLeads: 198, corporateLeads: 85,
    totalLeads: 1551, costPerLead: 12.54, newCustomers: 326, clientDatabase: 1284,
  },
  newVsRepeat: { new: 326, repeat: 530 },
  topChannel: 'WhatsApp',
  clienteling: { vipEvents: 3, lookbooks: 146, broadcasts: 12, invitations: 328, rsvpRate: 32, appointments: 48 },
  customerIntelligence: {
    topObjections: [
      { reason: 'Price', pct: 34 },
      { reason: 'Size Unavailable', pct: 22 },
      { reason: 'Waiting for Salary', pct: 18 },
      { reason: 'Comparing Options', pct: 14 },
      { reason: 'Need Approval', pct: 12 },
    ],
    competitorMentions: [
      { brand: 'Boggi', pct: 29 },
      { brand: 'Zara', pct: 21 },
      { brand: 'Hugo Boss', pct: 17 },
      { brand: 'LC Waikiki', pct: 13 },
      { brand: 'Nike', pct: 11 },
    ],
    topProductRequests: ['New Suits', 'Loafers', 'Large Handbags', 'Linen Shirts', 'White Sneakers'],
  },
  priorities: [
    { task: 'Drive awareness for Arbiter Collection', keyAction: 'Phase 2 Content Push', owner: 'Digital Team', deadline: '03 Jun 2026', status: 'In Progress' },
    { task: 'Grow WhatsApp leads by 25%', keyAction: 'Influencer Collaborations', owner: 'Brand Team', deadline: '05 Jun 2026', status: 'In Progress' },
    { task: 'Increase VIP engagement & appointments', keyAction: 'Arbiter Experience Night', owner: 'Clienteling Team', deadline: '07 Jun 2026', status: 'Planned' },
    { task: 'Improve VM compliance in all stores', keyAction: 'Store VM Refresh', owner: 'Marketing Ops', deadline: '06 Jun 2026', status: 'In Progress' },
    { task: 'Launch Father\'s Day Campaign', keyAction: 'Father\'s Day Campaign Launch', owner: 'Brand Team', deadline: '10 Jun 2026', status: 'Planned' },
  ],
  teamPerformance: [
    { metric: 'Campaign Execution', value: 85, status: 'On Track' },
    { metric: 'Content Delivery', value: 90, status: 'On Track' },
    { metric: 'Lead Generation', value: 78, status: 'At Risk' },
    { metric: 'Client Engagement', value: 82, status: 'On Track' },
  ],
};

export const operationsData: OperationsData = {
  storeOpsScore: { pct: 86, target: 90 },
  vmCompliance: { pct: 84, target: 90 },
  storeReadiness: { pct: 88, target: 90 },
  maintenanceCompliance: { pct: 78, target: 90 },
  sopCompliance: { pct: 85, target: 90 },
  cxScore: { pct: 83, target: 90 },
  openIssues: 48,
  storeOverview: [
    { rank: 1, name: 'Dzorwulu Men', opsScore: 92, vmScore: 90, readiness: 95, cxScore: 91 },
    { rank: 2, name: 'East Legon Men', opsScore: 89, vmScore: 87, readiness: 92, cxScore: 88 },
    { rank: 3, name: 'Labore Men', opsScore: 87, vmScore: 84, readiness: 88, cxScore: 86 },
    { rank: 4, name: 'Boulevard Women Labore', opsScore: 85, vmScore: 82, readiness: 87, cxScore: 84 },
    { rank: 5, name: 'Boulevard Women Dzorwulu', opsScore: 82, vmScore: 78, readiness: 85, cxScore: 80 },
    { rank: 6, name: 'D\'Angelo Palace', opsScore: 76, vmScore: 71, readiness: 80, cxScore: 78 },
    { rank: 7, name: 'Woodpeckers', opsScore: 75, vmScore: 68, readiness: 77, cxScore: 74 },
  ],
  vmByStore: [
    { store: 'Dzorwulu Men', compliance: 95 },
    { store: 'East Legon Men', compliance: 88 },
    { store: 'Labore Men', compliance: 86 },
    { store: 'Boulevard Women Dzorwulu', compliance: 78 },
    { store: 'Woodpeckers', compliance: 68 },
  ],
  maintenanceOrders: { open: 62, completed: 15, overdue: 7, critical: 7 },
  deployment: {
    completion: 87,
    categories: [
      { name: 'New Arrivals', planned: 12, completed: 11 },
      { name: 'Campaign Items', planned: 12, completed: 5 },
      { name: 'Visual Merchandising', planned: 6, completed: 6 },
      { name: 'Promotional Items', planned: 4, completed: 4 },
    ]
  },
  readinessIssues: [
    { store: 'D\'Angelo Palace', issue: 'Cashier Shortage', impact: 'High', status: 'In Progress' },
    { store: 'D\'Angelo Palace', issue: 'Safe Not Working', impact: 'High', status: 'In Progress' },
    { store: 'Boulevard Women Labore', issue: 'Opening Delay', impact: 'Medium', status: 'In Progress' },
    { store: 'Labore Men', issue: 'Staff Training Pending', impact: 'Medium', status: 'Planned' },
  ],
  cxFeedbackThemes: [
    { theme: 'Store Cleanliness', count: 142 },
    { theme: 'Staff Knowledge', count: 128 },
    { theme: 'Product Availability', count: 117 },
    { theme: 'Fitting Room Experience', count: 95 },
    { theme: 'Checkout Speed', count: 82 },
  ],
  sopAreas: [
    { area: 'Opening Procedures', compliance: 90 },
    { area: 'Sales Floor Standards', compliance: 88 },
    { area: 'Cash Handling', compliance: 85 },
    { area: 'Customer Service', compliance: 82 },
    { area: 'Closing Procedures', compliance: 80 },
    { area: 'Loss Prevention', compliance: 78 },
  ],
  incidents: { total: 19, security: 5, safety: 3, operational: 7 },
  riskLevel: { high: 3, medium: 11, low: 5 },
  actions: [
    { action: 'Fix AC at Woodpeckers', owner: 'Facilities Team', deadline: '31 May 2026', priority: 'Critical', status: 'In Progress' },
    { action: 'Update Window Display - D\'Angelo Palace', owner: 'VM Team', deadline: '31 May 2026', priority: 'High', status: 'In Progress' },
    { action: 'Staff Training - Cash handling', owner: 'HR', deadline: '01 Jun 2026', priority: 'High', status: 'In Progress' },
    { action: 'Fire Extinguisher Check All Stores', owner: 'Facilities Team', deadline: '02 Jun 2026', priority: 'Medium', status: 'Planned' },
    { action: 'Update Campaign POS in 3 Stores', owner: 'Marketing Ops', deadline: '01 Jun 2026', priority: 'Medium', status: 'In Progress' },
  ],
};

export const inventoryData: InventoryData = {
  totalValue: { current: 1180000, change: 4.8 },
  turnRate: { value: 2.48, target: 3.0 },
  sellThrough: { pct: 68.3, target: 75 },
  gmroi: { value: 2.48, target: 3.0 },
  weeksCover: { value: 14.2, target: '10-12' },
  deadStockPct: { pct: 11.9, target: '< 8%' },
  outOfStock: 126,
  accuracy: { pct: 98.2, target: 98 },
  valueTrend: [
    { month: 'Dec', value: 920000 },
    { month: 'Jan', value: 980000 },
    { month: 'Feb', value: 1020000 },
    { month: 'Mar', value: 1130000 },
    { month: 'Apr', value: 1080000 },
    { month: 'May', value: 1180000 },
  ],
  byBrand: [
    { name: 'Boulevard Men', value: 42 },
    { name: 'Boulevard Women', value: 16 },
    { name: 'D\'Angelo', value: 18 },
    { name: 'Woodpeckers', value: 12 },
    { name: 'Carbon Shoes', value: 7 },
    { name: 'Others', value: 5 },
  ],
  healthByAge: [
    { range: '0-30 Days', pct: 18.6 },
    { range: '31-60 Days', pct: 22.4 },
    { range: '61-90 Days', pct: 21.3 },
    { range: '91-180 Days', pct: 26.0 },
    { range: '180+ Days', pct: 11.9 },
  ],
  byCategory: [
    { name: 'Suits', value: 286400, pctTotal: 24.3, weeksCover: 12.4, sellThrough: 71.2 },
    { name: 'Shoes', value: 248700, pctTotal: 21.1, weeksCover: 10.8, sellThrough: 72.5 },
    { name: 'Shirts', value: 167200, pctTotal: 14.2, weeksCover: 13.6, sellThrough: 66.1 },
    { name: 'Blazers', value: 124600, pctTotal: 10.6, weeksCover: 16.2, sellThrough: 58.0 },
    { name: 'Bags', value: 103200, pctTotal: 8.8, weeksCover: 11.5, sellThrough: 70.3 },
    { name: 'Denim & Casual', value: 85800, pctTotal: 7.3, weeksCover: 12.1, sellThrough: 64.6 },
    { name: 'Accessories', value: 52600, pctTotal: 4.5, weeksCover: 8.3, sellThrough: 73.8 },
    { name: 'Others', value: 30700, pctTotal: 2.6, weeksCover: 9.7, sellThrough: 68.9 },
  ],
  slowMoving: [
    { rank: 1, sku: 'ARB-101-BLK-42', description: 'Arbiter Oxford Black 42', category: 'Shoes', value: 4820, days: 132 },
    { rank: 2, sku: 'BLA-201-NVY-50', description: 'Blazer Classic Navy 50', category: 'Blazers', value: 4260, days: 118 },
    { rank: 3, sku: 'SHI-302-WHT-L', description: 'Shirt White Linen L', category: 'Shirts', value: 3450, days: 104 },
    { rank: 4, sku: 'BAG-501-BRN', description: 'Leather Bag Brown', category: 'Bags', value: 3280, days: 98 },
    { rank: 5, sku: 'TRS-701-GRY-36', description: 'Trouser Grey 36', category: 'Trousers', value: 2980, days: 95 },
  ],
  deadStockItems: [
    { rank: 1, sku: 'BLA-201-BRG-52', description: 'Blazer Burgundy 52', category: 'Blazers', value: 8220, days: 245 },
    { rank: 2, sku: 'SWE-901-NVY-L', description: 'Sweater Knit Navy L', category: 'Sweaters', value: 6800, days: 223 },
    { rank: 3, sku: 'PJS-100-GRY-M', description: 'Pajama Set Grey M', category: 'Pajamas', value: 5450, days: 210 },
    { rank: 4, sku: 'WAT-601-BLK', description: 'Watch Classic Black', category: 'Watches', value: 4950, days: 198 },
    { rank: 5, sku: 'SHOE-900-BRG-43', description: 'Formal Shoe Burgundy', category: 'Shoes', value: 3950, days: 186 },
  ],
  storeAccuracy: [
    { store: 'Dzorwulu Men', accuracy: 98.6 },
    { store: 'East Legon Men', accuracy: 98.1 },
    { store: 'Labore Men', accuracy: 97.6 },
    { store: 'Boulevard Women Labore', accuracy: 98.4 },
    { store: 'Boulevard Women Dzorwulu', accuracy: 97.9 },
    { store: 'D\'Angelo Palace', accuracy: 98.3 },
    { store: 'Woodpeckers', accuracy: 98.0 },
  ],
  movement: { opening: 1090000, received: 286400, sold: 650482, returns: 18240, transfers: 14630, closing: 1180000 },
  replenishment: [
    { status: 'On Order (Not Received)', pos: 23, value: 312600 },
    { status: 'Partially Received', pos: 11, value: 148300 },
    { status: 'Delayed', pos: 5, value: 62700 },
  ],
  optimizationActions: [
    { action: 'Clear dead stock (180+ days)', priority: 'High', owner: 'Commercial', deadline: '07 Jun 2026', status: 'In Progress' },
    { action: 'Markdown plan for slow movers', priority: 'High', owner: 'Commercial', deadline: '10 Jun 2026', status: 'Planned' },
    { action: 'Rebalance stock across stores', priority: 'Medium', owner: 'Operations', deadline: '05 Jun 2026', status: 'In Progress' },
    { action: 'Increase fast moving SKUs', priority: 'Medium', owner: 'Buying', deadline: '12 Jun 2026', status: 'Planned' },
    { action: 'Improve size ratio for suits', priority: 'Low', owner: 'Buying', deadline: '10 Jun 2026', status: 'On Track' },
  ],
};

export const brandData: BrandData = {
  healthIndex: { score: 81, vsLastMonth: 4, vsLastYear: 9 },
  portfolio: [
    { brand: 'Boulevard Men', score: 88, status: 'Strong', trend: 'up' },
    { brand: 'Boulevard Women', score: 74, status: 'Watch', trend: 'up' },
    { brand: 'D\'Angelo', score: 67, status: 'Watch', trend: 'down' },
    { brand: 'Woodpeckers', score: 71, status: 'Strong', trend: 'up' },
    { brand: 'Carbon Shoes', score: 82, status: 'Strong', trend: 'stable' },
  ],
  equity: { awareness: 84, consideration: 78, preference: 76, loyalty: 72, advocacy: 69 },
  shareOfConversation: [
    { brand: 'Statestreet Brands', pct: 32 },
    { brand: 'Boggi', pct: 18 },
    { brand: 'Zara', pct: 14 },
    { brand: 'Hugo Boss', pct: 11 },
    { brand: 'LC Waikiki', pct: 9 },
    { brand: 'Nike', pct: 8 },
    { brand: 'Adidas', pct: 5 },
    { brand: 'Others', pct: 3 },
  ],
  sentiment: {
    positive: 68, neutral: 22, negative: 10,
    trend: [
      { month: 'Dec', score: 62 },
      { month: 'Jan', score: 64 },
      { month: 'Feb', score: 65 },
      { month: 'Mar', score: 66 },
      { month: 'Apr', score: 67 },
      { month: 'May', score: 68 },
    ]
  },
  marketPosition: [
    { brand: 'Hugo Boss', pricePosition: 85, perceivedQuality: 90 },
    { brand: 'Boulevard Men', pricePosition: 70, perceivedQuality: 82 },
    { brand: 'Boggi', pricePosition: 75, perceivedQuality: 78 },
    { brand: 'D\'Angelo', pricePosition: 60, perceivedQuality: 72 },
    { brand: 'Zara', pricePosition: 50, perceivedQuality: 60, isCompetitor: true },
    { brand: 'Woodpeckers', pricePosition: 55, perceivedQuality: 68 },
    { brand: 'Carbon Shoes', pricePosition: 65, perceivedQuality: 70 },
  ],
  momentumDrivers: [
    { driver: 'Marketing Campaigns', score: 91 },
    { driver: 'Traffic Generation', score: 74 },
    { driver: 'Conversion Improvement', score: 63 },
    { driver: 'Customer Engagement', score: 78 },
    { driver: 'Online Visibility', score: 69 },
    { driver: 'Sales Momentum', score: 83 },
    { driver: 'Brand Advocacy', score: 71 },
  ],
  merchandiseBrandHealth: [
    { brand: 'Arbiter', awareness: 88, consideration: 82, preference: 85, satisfaction: 78, momentum: 84, score: 84 },
    { brand: 'Gianfranco Butteri', awareness: 82, consideration: 78, preference: 80, satisfaction: 82, momentum: 76, score: 80 },
    { brand: 'Oliver Scotts', awareness: 75, consideration: 72, preference: 74, satisfaction: 76, satisfaction2: 70, momentum: 73, score: 73 },
    { brand: 'Gianni Gallucci', awareness: 70, consideration: 68, preference: 69, satisfaction: 72, momentum: 65, score: 69 },
    { brand: 'Cucinera Fiorentina', awareness: 78, consideration: 74, preference: 76, satisfaction: 79, momentum: 72, score: 76 },
    { brand: 'Zecca Milano', awareness: 78, consideration: 71, preference: 72, satisfaction: 75, momentum: 68, score: 72 },
  ],
  customerVoice: {
    compliments: ['Love the Italian shoes', 'Helpful and knowledgeable staff', 'Premium and stylish collections', 'New collections are exciting', 'Excellent after-sales service'],
    frustrations: ['Hard to locate sizes', 'Women\'s assortment feels repetitive', 'Inconsistent staff engagement', 'Price perception is high', 'Limited size availability'],
    emergingThemes: ['Loafers demand increasing', 'Interest in linen / seersucker styles', 'More demand for travel bags', 'Sustainability matters to customers', 'Looking for capsule wardrobe'],
  },
  categoryHealth: [
    { category: 'Footwear', health: 91, trend: 'up' },
    { category: 'Suits', health: 87, trend: 'up' },
    { category: 'Shirts', health: 84, trend: 'stable' },
    { category: 'Bags & Accessories', health: 76, trend: 'down' },
    { category: 'Dresses', health: 58, trend: 'down' },
    { category: 'Casual Wear', health: 66, trend: 'stable' },
  ],
  digitalReputation: { googleRating: 4.6, instaSentiment: 72, responseRate: 96, nps: 61 },
  socialMedia: { reach: 1240000, engagement: 142000, webVisits: 89000, leadsGenerated: 1551 },
  brandWeather: [
    { brand: 'Boulevard Men', weather: 'Sunny', impact: '+8% Revenue, +6% ATV', driver: 'Arbiter launch' },
    { brand: 'Boulevard Women', weather: 'Partly Cloudy', impact: '-6% Traffic, +3% Conversion', driver: 'New arrivals' },
    { brand: 'D\'Angelo', weather: 'Cloudy', impact: '-3% Revenue, -2% Conversion', driver: 'Assortment refresh' },
    { brand: 'Woodpeckers', weather: 'Improving', impact: '+12% Traffic, +10% Engagement', driver: 'New street campaign' },
    { brand: 'Carbon Shoes', weather: 'Sunny', impact: '+10% Revenue, +8% ATV', driver: 'New styles' },
  ],
  risks: [
    'Boulevard Women losing momentum',
    'Price perception affecting conversion',
    'Low UPT across women\'s stores',
    'Competitor promotions impacting traffic',
    'Dead stock building in seasonal categories',
  ],
  opportunities: [
    'Leverage Arbiter / Italian heritage story',
    'Expand clienteling & appointment sales',
    'Grow loafer category across brands',
    'Increase digital content for D\'Angelo',
    'Sustainability positioning differentiation',
  ],
  ceoAttention: [
    { priority: 'P1', issue: 'Boulevard Women momentum', impact: 'High Revenue Risk', owner: 'Commercial Director', dueDate: '7 Days', status: 'In Progress' },
    { priority: 'P1', issue: 'GHS 112M tied in slow moving', impact: 'Cash & Margin Risk', owner: 'Inventory Director', dueDate: 'Immediate', status: 'In Progress' },
    { priority: 'P2', issue: 'Low traction in D\'Angelo', impact: 'Brand Perception Risk', owner: 'Mktg Director', dueDate: '14 Days', status: 'Planned' },
    { priority: 'P2', issue: 'Woodpeckers content lagging', impact: 'Revenue Risk', owner: 'Brand Director', dueDate: '14 Days', status: 'In Progress' },
    { priority: 'P3', issue: 'Advocacy score declining', impact: 'Long Term Brand Risk', owner: 'Marketing Director', dueDate: '30 Days', status: 'Planned' },
  ],
};
